Scheduler needs to run on check instances
Received error:
TypeError: unbound method run() must be called with ActiveAdWordsCustomerPMsCheck instance as first argument (got nothing instead)